name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  cabal:
    name: cabal ${{ matrix.os }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        cabal:
          - "3.10"
        ghc:
          - 9.2.8
          - 9.4.8
          - 9.6.6
          - 9.8.2
          - 9.10.1
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Haskell Cabal
        uses: haskell-actions/setup@v2
        id: setup-haskell-cabal
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

      - uses: actions/cache@v4
        name: Cache ~/.cabal/store
        with:
          path: ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}

      - name: Build
        run: cabal build --enable-tests --enable-benchmarks --write-ghc-environment-files=always

      - name: Test
        run: cabal test --enable-tests

  stack:
    name: ${{ matrix.os }} / ${{ matrix.stack-yaml }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        stack:
          - 2.15.5
        stack-yaml:
          - stack-9.2.8.yaml
          - stack-9.4.8.yaml
          - stack-9.6.6.yaml
          - stack-9.8.2.yaml
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: haskell-actions/setup@v2
        name: Setup Haskell Stack
        with:
          stack-version: ${{ matrix.stack }}

      - uses: actions/cache@v4
        name: Cache ~/.stack
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ matrix.stack-yaml }}

      - name: Install dependencies
        run: stack build --stack-yaml ${{ matrix.stack-yaml }} --test --bench --no-run-tests --no-run-benchmarks --only-dependencies

      - name: Build
        run: stack build --stack-yaml ${{ matrix.stack-yaml }} --test --bench --no-run-tests --no-run-benchmarks

      - name: Test
        run: stack test --stack-yaml ${{ matrix.stack-yaml }}
