name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  cabal:
    name: cabal ${{ matrix.os }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          #- macOS-latest
          #- windows-latest
        cabal: [3.4]
        ghc:
          - 8.6.5
          - 8.8.4
          - 8.10.7
        #exclude:
        # Test only with latest GHC on windows and macOS
        # - os: macOS-latest
        #   ghc: 8.6.5
        # - os: macOS-latest
        #   ghc: 8.8.4
        # - os: windows-latest
        #   ghc: 8.6.5
        # - os: windows-latest
        #   ghc: 8.8.4
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: helloci
          POSTGRES_DB: pg_named
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
        if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/master'

      - uses: haskell/actions/setup@v1
        id: setup-haskell-cabal
        name: Setup Haskell Cabal
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

      - uses: actions/cache@v2
        name: Cache ~/.cabal/store
        with:
          path: ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}

      - name: Build
        run: cabal build --enable-tests --enable-benchmarks --write-ghc-environment-files=always

      - name: Test
        run: cabal test --enable-tests

  stack:
    name: ${{ matrix.stack-yaml }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stack:
          - 2.7.3
        stack-yaml:
          - stack-8.6.5.yaml
          - stack-8.8.4.yaml
          - stack-8.10.7.yaml
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: helloci
          POSTGRES_DB: pg_named
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
        if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/master'

      - uses: haskell/actions/setup@v1
        name: Setup Haskell Stack
        with:
          stack-version: ${{ matrix.stack }}

      - uses: actions/cache@v2
        name: Cache ~/.stack
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ matrix.stack-yaml }}

      - name: Install dependencies
        run: stack build --stack-yaml ${{ matrix.stack-yaml }} --test --bench --no-run-tests --no-run-benchmarks --only-dependencies

      - name: Build
        run: stack build --stack-yaml ${{ matrix.stack-yaml }} --test --bench --no-run-tests --no-run-benchmarks

      - name: Test
        run: stack test --stack-yaml ${{ matrix.stack-yaml }}
