name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  stack:
    name: stack / ghc ${{ matrix.ghc }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stack:
          - 2.7.3
        stack-yaml:
          - stack-8.6.5.yaml
          - stack-8.8.4.yaml
          - stack-8.10.7.yaml
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: helloci
          POSTGRES_DB: pg_named
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
        if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/master'

      - uses: haskell/actions/setup@v1
        name: Setup Haskell Stack
        with:
          stack-version: ${{ matrix.stack }}

      - uses: actions/cache@v2
        name: Cache ~/.stack
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ matrix.stack-yaml }}

      - name: Install dependencies
        run: stack build --stack-yaml ${{ matrix.stack-yaml }} --test --bench --no-run-tests --no-run-benchmarks --only-dependencies

      - name: Build
        run: stack build --stack-yaml ${{ matrix.stack-yaml }} --test --bench --no-run-tests --no-run-benchmarks

      - name: Test
        run: stack test --stack-yaml ${{ matrix.stack-yaml }}
